(ns intro-to-clojure.project-euler)

;; PROBLEM 1
;; If we list all the natural numbers below 10 that are
;; multiples of 3 or 5, we get 3, 5, 6 and 9.
;; The sum of these multiples is 23.
;;
;; Find the sum of all the multiples of 3 or 5 below 1000.
(defn divisor?
  [x d]
  (= 0 (rem x d)))
(def answer-1
  (let [xs (range 1000)
        d3 #(divisor? % 3)
        d5 #(divisor? % 5)
        ys (filter #(and (d3 %) (d5 %)) xs)]
    (reduce + ys)))
answer-1

;; PROBLEM 2
;; Each new term in the Fibonacci sequence is generated by
;; adding the previous two terms. By starting with 1 and 2,
;; the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values
;; do not exceed four million, find the sum of the even-valued terms.
(defn lazy-fib-seq
  []
  (let [next-fib-pair
        (fn [[a b]]
          [b (+ a b)])]
    (map first (iterate next-fib-pair [1 1]))))

(def answer-2
  (let [fibs      (lazy-fib-seq)
        even-fibs (filter even? fibs)
        under-4m  (take-while #(< % 4000000) even-fibs)]
    (reduce + under-4m)))
answer-2

;; PROBLEM 3
;; The prime factors of 13195 are 5, 7, 13 and 29.
;; What is the largest prime factor of the number 600851475143 ?
(defn get-max-prime-factor [num cur limit]
  (if (> cur limit)
    num
    (if (= num cur)
        num
        (if (zero? (mod num cur))
          (get-max-prime-factor (/ num cur) cur limit)
          (get-max-prime-factor num (inc cur) limit)))))

(defn max-prime-factor [num]
    (let [limit (long (Math/sqrt num))]
        (get-max-prime-factor num 2 limit)))
(def answer-3
  (max-prime-factor  600851475143))
answer-3



;; PROBLEM 4
;; A palindromic number reads the same both ways. The largest palindrome made from the product
;; of two 2-digit numbers is 9009 = 91 × 99.
;; Find the largest palindrome made from the product of two 3-digit numbers.
(defn palindrome? [s]
  (= (reverse (str s) ) (seq (str s))))

(def answer-4 (apply max
       (filter palindrome?
               (for
                   [a (range 100 1000)
                    b (range 100 1000)]
                 (* a b)))))
answer-4

;; PROBLEM 5
;; 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without
;; any remainder.
;; What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

(defn gcd
  [a b]
  (if (zero? b) a (recur b (mod a b))))

(defn lcm
  [a b]
  (/ (* a b) (gcd a b)))

(def answer-5
  (reduce #(lcm %1 %2) (range 1 21)))
answer-5

